"""Generate theme/static/css/palettes.css.

Two axes, so the palette is generated rather than written out by hand:

  mode  how light the page is       dark / mid / light
  hue   which colour the neutrals and the accent are built from   blue / silver

Each mode is a ramp of (saturation, lightness) targets per token; each hue
supplies an angle and a saturation multiplier. Silver is simply a hue whose
multiplier is near zero. No combination can drift internally inconsistent, and
changing the whole look is a table edit.

Ported from the prototype's theme.py, cut from fifteen combinations to six —
every combination has to be contrast-audited, and six is a finite audit.
"""
import colorsys
from pathlib import Path

MODES = ("dark", "mid", "light")
HUES = ("blue", "silver")

# token -> (saturation, lightness) per mode. This table is the design.
MODE_SPEC = {
    "dark": dict(bg=(14, 12), pan=(14, 10), r=(12, 24), r2=(12, 17),
                 fg=(10, 90), fg2=(10, 73), m=(8, 55), m2=(8, 45),
                 hv=(14, 16), sel=(28, 19), selb=(30, 32), code=(14, 9),
                 a=(95, 70), tint=(50, 30)),
    "mid": dict(bg=(12, 20), pan=(12, 18), r=(11, 32), r2=(11, 25),
                fg=(12, 93), fg2=(11, 80), m=(9, 63), m2=(9, 54),
                hv=(12, 24), sel=(24, 26), selb=(28, 40), code=(12, 17),
                a=(95, 77), tint=(50, 36)),
    "light": dict(bg=(12, 89), pan=(12, 85), r=(12, 72), r2=(12, 80),
                  fg=(18, 11), fg2=(14, 27), m=(10, 45), m2=(10, 56),
                  hv=(12, 84), sel=(30, 82), selb=(32, 66), code=(12, 85),
                  a=(85, 32), tint=(50, 30)),
}

# High contrast pushes text to the extremes and strengthens the rules.
# Opt-in, not a default: it changes the design the rounds actually settled on.
MODE_HC = {
    "dark": dict(fg=(0, 100), fg2=(6, 94), m=(6, 78), m2=(6, 70),
                 r=(14, 42), r2=(14, 34), a=(100, 80)),
    "mid": dict(fg=(0, 100), fg2=(6, 95), m=(7, 80), m2=(7, 72),
                r=(14, 48), r2=(14, 40), a=(100, 84)),
    "light": dict(fg=(0, 0), fg2=(10, 10), m=(10, 28), m2=(10, 34),
                  r=(14, 48), r2=(14, 58), a=(95, 24)),
}

# Status green stays semantic, so it does not follow the hue.
MODE_OK = {"dark": "#57ab5a", "mid": "#6cc26c", "light": "#26703a"}

HUE_SPEC = {
    "blue": dict(h=212, mul=1.00),
    "silver": dict(h=215, mul=0.22),
}


def _hex(h, s, lightness):
    r, g, b = colorsys.hls_to_rgb(
        (h % 360) / 360.0,
        max(0, min(100, lightness)) / 100.0,
        max(0, min(100, s)) / 100.0,
    )
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def palette(mode, hue, contrast=False):
    spec = dict(MODE_SPEC[mode])
    if contrast:
        spec.update(MODE_HC[mode])
    h, mul = HUE_SPEC[hue]["h"], HUE_SPEC[hue]["mul"]
    tokens = {k: _hex(h, s * mul, lightness) for k, (s, lightness) in spec.items()}
    tokens["ok"] = MODE_OK[mode]
    return tokens


def block(mode, hue, contrast):
    sel = f':root[data-mode="{mode}"][data-hue="{hue}"]'
    if contrast:
        sel += '[data-contrast="on"]'
    lines = [f"  --{k}: {v};" for k, v in palette(mode, hue, contrast).items()]
    return sel + " {\n" + "\n".join(lines) + "\n}"


def main():
    out = ["/* GENERATED by tools/palettes.py — do not edit. Edit the table there. */"]
    for contrast in (False, True):
        for mode in MODES:
            for hue in HUES:
                out.append(block(mode, hue, contrast))
    dest = Path(__file__).parent.parent / "theme" / "static" / "css" / "palettes.css"
    dest.write_text("\n\n".join(out) + "\n")
    print(f"  {dest.relative_to(Path.cwd())}: "
          f"{len(MODES) * len(HUES)} palettes x 2 contrast states")


if __name__ == "__main__":
    main()
